### ISSUE TITLE
cucc

### ISSUE THREAD

**Issue by taplonaplo** [zolcsieles/VRTestApp#1]
1. Mappa struktura nem jo: Data-ba kell a Shaders meg Textures
2. A simple.fs-ben ambigous call van. A clampedben vec3(float, float64,float64) van. Vagy a precison a vec3on legyen double, vagy explicit .f a floatok vegere h floatok legyenek

Nalam az opengl screencap nem ment, fekete kep

**Comment by zolcsieles** [comment]
Köszönöm az észrevételeket!
Az 1. pontot javítottam, 36-os release-ben már megfelelően vannak a mappák.
A 2-es pontra hogy sikerült rájönni? Kiírta valami vagy átnézted egyesével?
+1: A .tga file-ban is teljesen feketének látszik, azaz 0x00 byte-okkal van tele vagy csak az alpha csatorna van esetleg fordítva?

**Comment by zolcsieles** [comment]
Nem volt megadva, hogy hány bit alpha-t szeretnék, így intel driverrel szépen létre is hozta a RGBA8888-as surface-t, de nvidia driverrel kihagyta az alpha-t, csak RGB888-as surface-t készített.

**Comment by zolcsieles** [comment]
Build 39-el már mindegyik problémának meg kellett szűnnie.

**Comment by taplonaplo** [comment]
ugynezki nacibb a shader compilerem, nvidias, tapasztalatbol az AMD meginkabb az.
Ja mukodik minden rendesen a 40-el.
